#
# This file is part of Mikrocode.
#

LIBDIR=../../lib/

BINARY=sysum
SOURCES=sysum.c

MCU=atmega8
MCU_ARCH=avr

# 8+ Mhz external crystal
LFUSE=0xCE
# default
HFUSE=0xD9

#
# Sets cpu frequency as a static number
#
CPU_FREQ=16000

include $(LIBDIR)skel.mk
