#
# This file is part of Mikrocode.
#

LIBDIR=../../lib/

BINARY=pcd8544_test
SOURCES=pcd8544_test.c pcd8544.c

MCU=atmega8
MCU_ARCH=avr

#
# Sets cpu frequency as a static number
#
CPU_FREQ=4000

# 4Mhz internal clock
HFUSE=0xd9
FUSE=0xf3

include $(LIBDIR)skel.mk
